In [2]:
# There are three ways to create model in tf.keras
# sequential API
# Function API
# model subclassing

import numpy as np
import tensorflow as tf
from tensorflow import keras
print(tf.__version__)

2.15.0


In [10]:
nb_classes = 10 # number of neurons
reshaped = 784  # number of input expected

model = tf.keras.Sequential()
model.add(keras.layers.Dense(nb_classes, input_shape=(reshaped, ), kernel_initializer='zeros', name = 'dense_layer', activation = keras.activations.softmax))
print(1)

1


The model is defined with the sequential API with 10 neurons and the weight is initialized to zeros with the softmax activation function. The ANN is only one layer and expecting an input with shape of 784 * 1

In [15]:
epochs = 200
batch_size = 128
verbose = 1
nb_classes = 10
n_hidden = 128
validation_split = 0.2
reshaped = 784

mnist = keras.datasets.mnist

(X_train, Y_train), (X_test, Y_test) = mnist.load_data()

# reshaping the images
X_train = X_train.reshape(60000, reshaped)
X_test = X_test.reshape(10000, reshaped)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

# normalize the inputs to be within [0, 1]
print(f"Before normalizing the X_train: {X_train[:10]}")
X_train /= 255
X_test /= 255
print(f"After normalizing the X_train: {X_train[:10]}")

print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')

# one hot representation of the labels
print(f"Before one hot encoding Y_train: {Y_train[:10]}")
Y_train = tf.keras.utils.to_categorical(Y_train, nb_classes)
Y_test = tf.keras.utils.to_categorical(Y_test, nb_classes)
print(f"After one hot encoding Y_train: {Y_train[: 10]}")


Before normalizing the X_train: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
After normalizing the X_train: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
60000 train samples
10000 test samples
Before one hot encoding Y_train: [5 0 4 1 9 2 1 3 1 4]
After one hot encoding Y_train: [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [17]:
# build the model
model = tf.keras.models.Sequential()
model.add(keras.layers.Dense(nb_classes, input_shape=(reshaped, ), name = "dense_layer_1", activation = keras.activations.softmax))

In [19]:
# compile the model

model.compile(optimizer="SGD", loss="categorical_crossentropy", metrics=['accuracy'])

In [20]:
# training the model
# epochs is the number of times the model is exposed to the training set
# batch_size is the number of  training instances observed before the optimizer updates the weight
model.fit(X_train, Y_train, batch_size=batch_size, epochs=epochs, verbose=verbose, validation_split=validation_split)

2024-03-05 02:49:45.750333: W external/local_tsl/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 150528000 exceeds 10% of free system memory.


Epoch 1/200
375/375 [==============================] - 4s 8ms/step - loss: 1.3910 - accuracy: 0.6576 - val_loss: 0.9027 - val_accuracy: 0.8200
Epoch 2/200
375/375 [==============================] - 3s 7ms/step - loss: 0.8006 - accuracy: 0.8254 - val_loss: 0.6606 - val_accuracy: 0.8553
Epoch 3/200
375/375 [==============================] - 3s 7ms/step - loss: 0.6479 - accuracy: 0.8478 - val_loss: 0.5639 - val_accuracy: 0.8672
Epoch 4/200
375/375 [==============================] - 3s 7ms/step - loss: 0.5743 - accuracy: 0.8587 - val_loss: 0.5104 - val_accuracy: 0.8763
Epoch 5/200
375/375 [==============================] - 3s 8ms/step - loss: 0.5296 - accuracy: 0.8660 - val_loss: 0.4756 - val_accuracy: 0.8823
Epoch 6/200
375/375 [==============================] - 3s 8ms/step - loss: 0.4988 - accuracy: 0.8719 - val_loss: 0.4512 - val_accuracy: 0.8882
Epoch 7/200
375/375 [==============================] - 3s 7ms/step - loss: 0.4761 - accuracy: 0.8768 - val_loss: 0.4327 - val_accuracy: 0.8900

In [21]:
score = model.evaluate(X_test, Y_test)
print("score: {}".format(score[1]))

313/313 [==============================] - 1s 4ms/step - loss: 0.2776 - accuracy: 0.9216
score: 0.9215999841690063


In [23]:
model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_layer_1 (Dense)       (None, 10)                7850      
                                                                 
Total params: 7850 (30.66 KB)
Trainable params: 7850 (30.66 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [3]:
import tensorflow as tf
from tensorflow import keras

#improving the accuracy by adding more layers
epochs = 50
batch_size = 128
verbose = 1
nb_classes = 10
n_hidden = 128
validation_split = 0.2

# loading the mnist data
mnist = keras.datasets.mnist
(X_train, Y_train), (X_test, Y_test) = mnist.load_data()

reshaped = 784

X_train = X_train.reshape(60000, reshaped)
X_test = X_test.reshape(10000, reshaped)

X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

#normalizing the data to be [0,1]
X_train /= 255
X_test /= 255

# one hot encoding the values
Y_train = keras.utils.to_categorical(Y_train, nb_classes)
Y_test = keras.utils.to_categorical(Y_test, nb_classes)


#build the model
model = keras.models.Sequential()
model.add(keras.layers.Dense(n_hidden, input_shape=(reshaped,), name="dense_layer_1", activation=keras.activations.relu))
model.add(keras.layers.Dense(n_hidden, name= "dense_layer_2", activation="relu"))
model.add(keras.layers.Dense(nb_classes, name="dense_layer_3", activation="softmax"))

# summary
model.summary()

# compiling the model
model.compile(optimizer="SGD", loss="categorical_crossentropy", metrics=['accuracy'])

# training the model
model.fit(X_train, Y_train, epochs=epochs, batch_size=batch_size, verbose=verbose, validation_split=validation_split)


#evaluating the model
score = model.evaluate(X_test, Y_test)
print("accuracy: ", score[1])

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_layer_1 (Dense)       (None, 128)               100480    
                                                                 
 dense_layer_2 (Dense)       (None, 128)               16512     
                                                                 
 dense_layer_3 (Dense)       (None, 10)                1290      
                                                                 
Total params: 118282 (462.04 KB)
Trainable params: 118282 (462.04 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/50
375/375 [==============================] - 3s 6ms/step - loss: 1.3995 - accuracy: 0.6501 - val_loss: 0.6830 - val_accuracy: 0.8509
Epoch 2/50
375/375 [==============================] - 2s 5ms/step - loss: 0.5611 - accuracy: 0.8606 - val_loss: 0.4311 - val_accuracy: 0

In [4]:
import tensorflow as tf
from tensorflow import keras

#improving the accuracy by adding more layers
epochs = 50
batch_size = 128
verbose = 1
nb_classes = 10
n_hidden = 128
validation_split = 0.2
dropout = 0.3  # dropping out some the features for the model to generalized very well

# loading the mnist data
mnist = keras.datasets.mnist
(X_train, Y_train), (X_test, Y_test) = mnist.load_data()

reshaped = 784

X_train = X_train.reshape(60000, reshaped)
X_test = X_test.reshape(10000, reshaped)

X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

#normalizing the data to be [0,1]
X_train /= 255
X_test /= 255

# one hot encoding the values
Y_train = keras.utils.to_categorical(Y_train, nb_classes)
Y_test = keras.utils.to_categorical(Y_test, nb_classes)


#build the model
model = keras.models.Sequential()
model.add(keras.layers.Dense(n_hidden, input_shape=(reshaped,), name="dense_layer_1", activation=keras.activations.relu))
model.add(keras.layers.Dropout(dropout))
model.add(keras.layers.Dense(n_hidden, name= "dense_layer_2", activation="relu"))
model.add(keras.layers.Dropout(dropout))
model.add(keras.layers.Dense(nb_classes, name="dense_layer_3", activation="softmax"))

# summary
model.summary()

# compiling the model
model.compile(optimizer="SGD", loss="categorical_crossentropy", metrics=['accuracy'])

# training the model
model.fit(X_train, Y_train, epochs=epochs, batch_size=batch_size, verbose=verbose, validation_split=validation_split)


#evaluating the model
score = model.evaluate(X_test, Y_test)
print("accuracy: ", score[1])

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_layer_1 (Dense)       (None, 128)               100480    
                                                                 
 dropout (Dropout)           (None, 128)               0         
                                                                 
 dense_layer_2 (Dense)       (None, 128)               16512     
                                                                 
 dropout_1 (Dropout)         (None, 128)               0         
                                                                 
 dense_layer_3 (Dense)       (None, 10)                1290      
                                                                 
Total params: 118282 (462.04 KB)
Trainable params: 118282 (462.04 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/50
375

Adding the dropout did not improve the previous score of the model. Therefore , testing with a different optimizer.

In [5]:
# using RMSprop as optimizer
import tensorflow as tf
from tensorflow import keras

#improving the accuracy by adding more layers
epochs = 50
batch_size = 128
verbose = 1
nb_classes = 10
n_hidden = 128
validation_split = 0.2

# loading the mnist data
mnist = keras.datasets.mnist
(X_train, Y_train), (X_test, Y_test) = mnist.load_data()

reshaped = 784

X_train = X_train.reshape(60000, reshaped)
X_test = X_test.reshape(10000, reshaped)

X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

#normalizing the data to be [0,1]
X_train /= 255
X_test /= 255

# one hot encoding the values
Y_train = keras.utils.to_categorical(Y_train, nb_classes)
Y_test = keras.utils.to_categorical(Y_test, nb_classes)


#build the model
model = keras.models.Sequential()
model.add(keras.layers.Dense(n_hidden, input_shape=(reshaped,), name="dense_layer_1", activation=keras.activations.relu))
#model.add(keras.layers.Dropout(dropout))
model.add(keras.layers.Dense(n_hidden, name= "dense_layer_2", activation="relu"))
#model.add(keras.layers.Dropout(dropout))
model.add(keras.layers.Dense(nb_classes, name="dense_layer_3", activation="softmax"))

# summary
model.summary()

# compiling the model
model.compile(optimizer="RMSProp", loss="categorical_crossentropy", metrics=['accuracy'])

# training the model
model.fit(X_train, Y_train, epochs=epochs, batch_size=batch_size, verbose=verbose, validation_split=validation_split)


#evaluating the model
score = model.evaluate(X_test, Y_test)
print("accuracy: ", score[1])

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_layer_1 (Dense)       (None, 128)               100480    
                                                                 
 dense_layer_2 (Dense)       (None, 128)               16512     
                                                                 
 dense_layer_3 (Dense)       (None, 10)                1290      
                                                                 
Total params: 118282 (462.04 KB)
Trainable params: 118282 (462.04 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/50
375/375 [==============================] - 3s 7ms/step - loss: 0.3375 - accuracy: 0.9024 - val_loss: 0.1634 - val_accuracy: 0.9518
Epoch 2/50
375/375 [==============================] - 2s 6ms/step - loss: 0.1415 - accuracy: 0.9578 - val_loss: 0.1269 - val_accuracy: 0

In [7]:

# using Adam as optimizers
import tensorflow as tf
from tensorflow import keras

#improving the accuracy by adding more layers
epochs = 10
batch_size = 128
verbose = 1
nb_classes = 10
n_hidden = 128
validation_split = 0.2

# loading the mnist data
mnist = keras.datasets.mnist
(X_train, Y_train), (X_test, Y_test) = mnist.load_data()

reshaped = 784

X_train = X_train.reshape(60000, reshaped)
X_test = X_test.reshape(10000, reshaped)

X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

#normalizing the data to be [0,1]
X_train /= 255
X_test /= 255

# one hot encoding the values
Y_train = keras.utils.to_categorical(Y_train, nb_classes)
Y_test = keras.utils.to_categorical(Y_test, nb_classes)


#build the model
model = keras.models.Sequential()
model.add(keras.layers.Dense(n_hidden, input_shape=(reshaped,), name="dense_layer_1", activation=keras.activations.relu))
#model.add(keras.layers.Dropout(dropout))
model.add(keras.layers.Dense(n_hidden, name= "dense_layer_2", activation="relu"))
#model.add(keras.layers.Dropout(dropout))
model.add(keras.layers.Dense(nb_classes, name="dense_layer_3", activation="softmax"))

# summary
model.summary()

# compiling the model
model.compile(optimizer="Adam", loss="categorical_crossentropy", metrics=['accuracy'])

# training the model
model.fit(X_train, Y_train, epochs=epochs, batch_size=batch_size, verbose=verbose, validation_split=validation_split)


#evaluating the model
score = model.evaluate(X_test, Y_test)
print("accuracy: ", score[1])

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_layer_1 (Dense)       (None, 128)               100480    
                                                                 
 dense_layer_2 (Dense)       (None, 128)               16512     
                                                                 
 dense_layer_3 (Dense)       (None, 10)                1290      
                                                                 
Total params: 118282 (462.04 KB)
Trainable params: 118282 (462.04 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/10
375/375 [==============================] - 3s 7ms/step - loss: 0.3641 - accuracy: 0.8965 - val_loss: 0.1770 - val_accuracy: 0.9487
Epoch 2/10
375/375 [==============================] - 2s 6ms/step - loss: 0.1474 - accuracy: 0.9556 - val_loss: 0.1431 - val_accuracy: 0